openapi: 3.0.0
info:
  title:  API
  version: 1.0.0
  description: A simple API for managing a list of todo items.
servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: http://localhost:8080/v1
    description: Local development server
tags:
  - name: conversation
    description: conversations api
paths:
  /conversations/:
    post:
      summary: create and update conversation
      tags:
        - conversation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Conversation'
      responses:
        '20':
          description: Todo item created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TodoItem'
  /conversation/{id}:
    get:
      summary: get a conversation
      tags:
        - conversation
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the todo item to retrieve
          schema:
            type: string
      responses:
        '200':
          description: A conversation item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '404':
          description: Todo item not found
components:
  schemas:
    TodoItem:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the todo item
        title:
          type: string
          description: The title of the todo item
        completed:
          type: boolean
          description: Indicates if the todo item is completed
          default: false
      required:
        - id
        - title
    NewTodoItem:
      type: object
      properties:
        title:
          type: string
          description: The title of the new todo item
      required:
        - title